title: Yash Tiwari
author:
  name:
  email: 
description: >- # this means to ignore newlines until "baseurl:"
  Unpolished personal musings on the intersection of math, 
  science and data science (some random stuff as well).

show_excerpts: false # set to true to show excerpts on the homepage
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "yashtx.github.io/blog" # the base hostname & protocol for your site, e.g. http://example.com

minima:
  date_format: "%b %-d, %Y"
  skin: solarized

  social_links:
    twitter: yashtx
    github:  yashtx

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag